default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_management_development
  username: postgres
  password: D3m1lad3

  host: localhost
  port: 5432

  
test:
  <<: *default
  database: project_management_test
  username: postgres
  password: D3m1lad3


production:
  <<: *default
  database: project_management_production
  username: postgres
  password: D3m1lad3
